# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd2c62a1f0ded84aee435e91e6ac830d8bd4df3a31a3ab0c2fc5b336f3516ed1497a371487d0f1a04dd34f4175bfee004f83aed460346efb0fa21c68ae50bab2

test:
  secret_key_base: 47f2d183d088060d8f835ec0356b59b355497b45e431ced1a46042d9d44cd6259efd18084df5398320378a3975ae89b7534d132a22f943aa08f6305ceaf80fdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
